### ISSUE TITLE
Kinetic Generator like emf-generator

### ISSUE THREAD

**Issue by hasokeric** [Epicor/Kinetic#3]
Hello @bparkhurst ,

Are there any plans in creating **kinetic-generator** similar to the **emf-generator** built on-top of Yeoman?

**Comment by bparkhurst** [comment]
Yes, Kinetic is going to have schematics that will be used with the Angular CLI for creating a new Kinetic application and Kinetic views.  It is in the works now, and will be coming soon to a Kinetic version.  Once we release the schematics, we will update the Kinetic documentation.

**Comment by hasokeric** [comment]
Sweet! I've been watching your progress and I love the fact you are using compodoc to document, it's very elegant. I also managed to get your stackblitz starter to work on Angular 6 https://stackblitz.com/edit/epicor-kinetic-starter - Keep up the good work.
